version: '3.8'

services:
  app:
    build: .
    container_name: EduAI
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eduAI_UIKTP
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - mynetwork

  db:
    image: postgres:16
    container_name: EduAI_db
    restart: always
    environment:
      POSTGRES_DB: eduAI_UIKTP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/create-tables.sql:/docker-entrypoint-initdb.d/EduAI.sql

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local