spring:
  application:
    name: EduAI
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
  fireworks:
    api:
      key: ${FIREWORKS_API_KEY}
  datasource:
    write:
      url: jdbc:postgresql://postgres-write.default.svc.cluster.local:5432/eduai
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    read:
      url: jdbc:postgresql://postgres-read.default.svc.cluster.local:5432/eduai
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework: DEBUG