spring:
  application:
    name: EduAI
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
  fireworks:
    api:
      key: ${FIREWORKS_API_KEY}
  datasource:
    write:
      jdbc-url: jdbc:postgresql://postgres-write.eduai.svc.cluster.local:5432/eduai
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
    read:
      jdbc-url: jdbc:postgresql://postgres-read.eduai.svc.cluster.local:5432/eduai
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: DEBUG