name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      BACKEND_REPO: ${{ secrets.DOCKER_USERNAME }}/eduai-backend
      FRONTEND_REPO: ${{ secrets.DOCKER_USERNAME }}/eduai-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate branch-date tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}-$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.BACKEND_REPO }}:${{ env.TAG }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_REPO }}:${{ env.TAG }}
